version: "1"
rules:
  # hardreset local master with upstream
  - base: master
    upstream: mbdavid:master
    mergeMethod: hardreset
  # create pull request when local master is updated
  - base: upm-convert
    upstream: master